### ISSUE TITLE
New type error for Pydantic v2 models in 0.21.4 release

### ISSUE THREAD

**Issue by willarmiros** [koxudaxi/datamodel-code-generator#1491]
**Describe the bug**
When upgrading from 0.21.3 -> 0.21.4, my Pydantic v2 models were generated in a slightly different way that involved using a `RootModel`, which in turn triggered a type error from MyPy.

**To Reproduce**

Example schema:
```json

{
    "openapi": "3.1.0",
    "info": {
        "title": "FastAPI",
        "version": "0.1.0"
    },
    "components": {
        "schemas": {
            "MySchema": {
                "properties": {
                    "name": {
                        "type": "string",
                        "title": "Name"
                    },
                    "uuid": {
                        "type": "string",
                        "title": "Uuid"
                    },
                    "external_uri": {
                        "anyOf": [
                            {
                                "type": "string"
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "title": "External Uri"
                    },
                    "description": {
                        "anyOf": [
                            {
                                "type": "string",
                                "maxLength": 256
                            },
                            {
                                "type": "null"
                            }
                        ],
                        "title": "Description"
                    }
                },
                "type": "object",
                "required": [
                    "name",
                    "uuid"
                ],
                "title": "MySchema"
            }
        },
        "securitySchemes": {
            "HTTPBearer": {
                "type": "http",
                "scheme": "bearer"
            }
        }
    }
}

```

Used commandline:
```
$ poetry run datamodel-codegen --input repro-openapi.json --input-file-type openapi --use-annotated --output-model-type "pydantic_v2.BaseModel" --base-class "pydantic.BaseModel" --output model.py
```

MyPy commands (using the latest MyPy 1.5.0, but this also happened with MyPy 1.4.1):

```
poetry run mypy --ignore-missing-imports --strict --check-untyped-defs .
````

And the error output:

```
model.py:13: error: Missing type parameters for generic type "RootModel"  [type-arg]
````

**Expected behavior**
Expected behavior is that no MyPy errors are raised as was the case before.

**Version:**
 - OS: Mac OSX
 - Python version: Python 3.11.3
 - datamodel-code-generator version: 0.21.4

**Additional context**

 I was able to resolve this issue by manually adding the type parameter to the RootModel base class, like so:

```python
# Original generated by datamodel-codegen
class DescriptionItem(RootModel):
    root: Annotated[str, Field(max_length=256)]

# My fix
class DescriptionItem(RootModel[str]):
    root: Annotated[str, Field(max_length=256)]
```

Of course manually adding this to the generated code is not a sustainable solution. I suspect this was caused by #1477, since that involved Pydantic v2 RootModels and was only just added in the latest release.

**Comment by BryceLohr** [comment]
Yup, I've got the same issue. This is the last outstanding problem we have after migrating our code base over to Pydantic V2.
